### ISSUE TITLE
Tasks list for release

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/project_browser#10]
Recommended remaining tasks so we can split up:
- [x] Ensure paging works. (Will require more projects in the json feed.)
- [x] Ensure browser sorting works
- [x] ~~Fix categories filters~~ _Disabled this till Backdrop actually has categories_
- [x] Code cleanup, including removing hook_autoload and hook_help
- [x] Security review - ensure user input escaped throughout
- [ ] https://github.com/backdrop-contrib/project_browser/issues/13: Add layout tab to browser and ensure layouts can be installed
- [x] https://github.com/backdrop-contrib/project_browser/issues/15: Add a default image icon (separate one for each project type)
- [x] Theming review
- [x] https://github.com/backdrop-contrib/project_browser/issues/11: Add a popup dialogue to view full details about a project and remove/trim browser description
- [x] https://github.com/backdrop-contrib/project_browser/issues/17: Add check for PHP Zip extension and disable install through project_browser if not?

Later release:
- [ ] Develop a ratings system
- [ ] Develop a system for comments
- [ ] ...

Any else? Comments

Edit: tagging names: @Drupaldise @Graham-72

**Comment by Drupaldise** [comment]
When I am not wrong my PR https://github.com/backdrop-contrib/project_browser/pull/7 will fix "Fix categories filters"

**Comment by Drupaldise** [comment]
Not for the first release BUT it would be really cool if we can create a rating and comment system for the projects...

**Comment by docwilmot** [comment]
> Not for the first release BUT it would be really cool if we can create a rating and comment system for the projects...

Added that to the task list.

**Comment by docwilmot** [comment]
Done a few PRs on this list so far, would appreciate some feedback if you have the time please before merging changes. 
Also tagging @wildkatana so you can have an eye on this please if you dont mind. Forgot to do so in first post.

**Comment by Graham-72** [comment]
I have just installed your latest versions and had some success in installing a couple of modules. Well done! I will do some more testing in the next day or so, perhaps adding some more project data, or are you nearly there with getting a dump from backdropcms.org?
I am wondering how to deal with situations where a project has additional modules within it. E.g. views_slideshow downloaded both but only installed the main one, but it is not a major problem since the other is there to tick.

**Comment by docwilmot** [comment]
Hi @Graham-72, its progressing. We've got the full feed on dev.backdropcms.org if you change your `project_browser_default_server` config as usual. I think the server is good enough now, just to finish the browser, although thats practically done too, just hoping for a review on those PRs I've posted. Thanks foe checking in.

**Comment by Graham-72** [comment]
@docwilmot OK, I now have the feed from dev.backdropcms. Excellent. I will make some time tomorrow to do some testing of PRs.

**Comment by docwilmot** [comment]
OK first push of browser server to backdropcms repo just done, awaiting review. So I need to finish this now. Will start merging these PRs in today starting with the zip check (thanks @Graham-72).

Will sadly have to leave out the layout additions (https://github.com/backdrop-contrib/project_browser/issues/13) as core update itself isnt ready to install layouts. I've sent a PR for that too.

**Comment by docwilmot** [comment]
And done.

Note that currently very few projects will appear in the browser (17 today) since it now only shows projects with a release. See https://github.com/backdrop-contrib/project_browser/issues/19#issuecomment-108850239

**Comment by klonos** [comment]
@docwilmot  & @Graham-72: Thanx you guys for all your efforts and time spent on this!

I'm not sure I'll use this feature, but it brings us closer to being in feature parity with competitors like Wordpress. Things that took ages to happen in Drupaland and frustrated both end users as well as people that contributed code/time but never saw it happening, now get to be done in a short period of time in Backdropland.

Thanx once again.
